### ISSUE TITLE
Does not ignore HTML comments

### ISSUE THREAD

**Issue by lobo-tuerto** [kawamataryo/vue-word-highlighter#687]
When you have HTML comments inside the highlighter, they get highlighted if they match the query.

Is it possible to ignore them completely?

**Comment by kawamataryo** [comment]
Thank you for your report issue.
I'll fix it. However, I am not feeling well right now, so I may be a little slow in fixing it.

**Comment by lobo-tuerto** [comment]
@kawamataryo Sorry to hear that.
Take it easy  and get well soon. :+1:

**Comment by kawamataryo** [comment]
@lobo-tuerto 

I fixed this issue. Would you please check the work in v1.2.3

**Comment by lobo-tuerto** [comment]
Hmm :thinking: 

I'm still seeing comments content presented and highlighted.

This is the code I'm using for test:

```html
<WordHighlighter :query="searchQuery">
  <!-- name or email -->
  {{ user.name }} - {{ user.email }}
</WordHighlighter>
```

When typing `na`  
And I see content like this:

```text
name or email some-name@email.com
```
